### ISSUE TITLE
Fix R CMD CHECK notes

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.osprey#202] opened 2023-03-20 10:07 UTC
```
* checking R code for possible problems ... NOTE
srv_g_heatmap_bygrade : <anonymous>: no visible binding for global
  variable ‘conmed_var_name’
srv_g_heatmap_bygrade : <anonymous>: no visible binding for global
  variable ‘conmed_level’
srv_g_heatmap_bygrade : <anonymous>: no visible binding for global
  variable ‘conmed_var’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘USUBJID’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘LSTALVDT’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘DTHDT’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘ASTDT’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘AENDT’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘ASTDY’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘AENDY’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘line_col’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘line_col_legend’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘line_col_opt’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘ADT’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘PARAMCD’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘PARAM’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘AVALC’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘AVAL’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘ADY’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘PARCAT1’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘PARCAT2’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘AVALU’
srv_g_patient_profile : <anonymous> : <anonymous>: no visible binding
  for global variable ‘PARCAT2’
srv_g_patient_profile : <anonymous> : <anonymous>: no visible binding
  for global variable ‘PARAMCD’
srv_g_patient_profile : <anonymous> : <anonymous>: no visible binding
  for global variable ‘ASTDT’
srv_g_patient_profile : <anonymous> : <anonymous>: no visible binding
  for global variable ‘AVAL’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘.’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘STUDYID’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘LBSEQ’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘BASETYPE’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘AVISITN’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘LBTESTCD’
srv_g_patient_profile : <anonymous>: no visible binding for global
  variable ‘ANRIND’
Undefined global functions or variables:
  . ADT ADY AENDT AENDY ANRIND ASTDT ASTDY AVAL AVALC AVALU AVISITN
  BASETYPE DTHDT LBSEQ LBTESTCD LSTALVDT PARAM PARAMCD PARCAT1 PARCAT2
  STUDYID USUBJID conmed_level conmed_var conmed_var_name line_col
  line_col_legend line_col_opt
```

**Comment by m7pr** [comment] 2023-06-28 07:37
working on it!

**Comment by m7pr** [comment] 2023-06-28 07:38
a duplicate of #211 - will work on it there

**Closed by m7pr** 2023-06-28 07:38 UTC
